### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by spirillen**
Initial ORG README to introduce the project (Front page)

This PR will also contains common issue template for bug (Live example at https://github.com/foreign-affairs/ITT/issues/new/choose (Choose Bug Report)

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Looks good to me @funilrys

**Review by funilrys — CHANGES_REQUESTED** [review]
Please switch your branch to `master`. Starting now, we will require all default branch to be named `master`. 

Otherwise, LGTM!

**Review by funilrys — APPROVED** [review]

**Comment by spirillen** [comment]
> be named master

Super, only choose main do to @mitchellkrogza usual default 😉  will be changed in later commit

**Comment by funilrys** [comment]
@spirillen already did :-)

**Comment by spirillen** [comment]
Noticed... 😒 

the conflict with my offline work was luckily limited to the README

**Comment by spirillen** [comment]
> Please switch your branch to `master`. Starting now, we will require all default branch to be named `master`.
> 
> Otherwise, LGTM!

@mitchellkrogza & @funilrys You should set this in "Repository default branch" https://github.com/Phishing-Database/settings/repository-defaults

**Comment by funilrys** [comment]
Already did :-)

**Pull request merged**
